---
title: "Modeling_part_draft"
author: "Bulun Te"
date: "2024-04-15"
output: 
  pdf_document:
    latex_engine: xelatex
  html_document:
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(patchwork)
setwd(here::here())
```


# Longitudinal Possion Regression with  random effect


## assuming 2307 is male and 5094 is female
```{r}


# constructing variable
load("complete_data3_2307_1_5094_0.RData")

complete_data  = complete_data %>% mutate(
  Pickups_lag_log = log(Pickups_lag),
  Total.ST.min.log = log(Total.ST.min),
  is_work_day = Semester * Xt,
  Treatment_Group = Treatment
  
)

complete_data <- complete_data %>% 
  group_by(pseudo_ID) %>% 
  mutate(success_lag = lag(success, order_by = Date),
         Total.ST.min.lag = lag(Total.ST.min, order_by = Date),
         Proportion.ST_lag = lag(Proportion.ST, order_by = Date))


library(lme4)

model_1 <-
  glmer(
    Pickups ~ Pickups_lag_log+ Treatment_Group + Phase + Proportion.ST +sex + is_work_day + devices  + (1 + Semester:Xt  |pseudo_ID ),
    data = complete_data,
    family = poisson(link = "log"),
    control = glmerControl(optCtrl = list(maxfun = 1e5),optimizer = "bobyqa")
  )

summary(model_1)
car::vif(model_1)

residuals(model_1) %>% as.data.frame() -> residuals_table

residuals_table %>% nrow()

std_resid = resid(model_1, type = "deviance")

plot(std_resid ~ fitted(model_1),ylab = "Standardized Residuals", xlab = "Fitted Values", main = "Standardized Residuals vs Fitted Values", col = "blue")

## qqplot

qqnorm(std_resid, main = "Normal Q-Q Plot", col = "blue")
qqline(std_resid, col = "red")


# redo the residual and qqplot using ggplot2 and patchwork and combine them together

p1 <- ggplot(residuals_table, aes(x = fitted(model_1), y = std_resid)) +
  geom_point(color = "blue") +
  geom_hline(yintercept = 0, linetype = "dashed", color = "red") +
  labs(x = "Fitted Values", y = "Standardized Residuals",
       title = "Standardized Residuals vs Fitted Values") +
  theme_minimal()

# QQ图
p2 <- ggplot(residuals_table, aes(sample = std_resid)) +
  stat_qq(color = "blue") +
  stat_qq_line(color = "red") +
  labs(x = "Theoretical Quantiles", y = "Sample Quantiles",
       title = "Normal Q-Q Plot") +
  theme_minimal()


#library(ggplot2)
#library(stringr)

coef_data <- data.frame(
  term = names(fixef(model_1)),
  estimate = fixef(model_1),
  conf.low = fixef(model_1) - 1.96 * sqrt(diag(vcov(model_1))),
  conf.high = fixef(model_1) + 1.96 * sqrt(diag(vcov(model_1)))
)


forest_plot <- ggplot(coef_data, aes(x = estimate, y = term, xmin = conf.low, xmax = conf.high)) +
  geom_point(size = 3) +
  geom_errorbarh(height = 0.2) +
  geom_vline(xintercept = 0, linetype = "dashed", color = "red") +
  theme_minimal() +
  theme(
    panel.grid.major.y = element_blank(),
    panel.grid.minor.y = element_blank(),
    axis.title.y = element_blank(),
    plot.title = element_text(hjust = 0.5)
  ) +
  xlab("Coefficient Estimate") +
  ggtitle("Forest Plot of Model Coefficients") +
  scale_y_discrete(labels = function(x) str_wrap(x, width = 20))


# ggsave("plots/forest_plot.png", plot = forest_plot, width = 8, height = 6, units = "in")


p1 + p2 +forest_plot + plot_layout(ncol = 3)  

#ggsave("plots/model_1_result.png", model_1_result, width = 10, height = 5)

```

## assuming 2307 is male and 5094 is male

```{r}

# constructing variable
load("complete_data3_2307_1_5094_1.RData")

complete_data  = complete_data %>% mutate(
  Pickups_lag_log = log(Pickups_lag),
  Total.ST.min.log = log(Total.ST.min)
)

complete_data <- complete_data %>% 
  group_by(pseudo_ID) %>% 
  mutate(success_lag = lag(success, order_by = Date),
         Total.ST.min.lag = lag(Total.ST.min, order_by = Date),
         Proportion.ST_lag = lag(Proportion.ST, order_by = Date))


library(lme4)

model_2 <-
  glmer(
    Pickups ~   Pickups_lag_log +  Treatment + Phase + Proportion.ST +sex + Semester:Xt + devices + sex:log(Total.ST.min.lag) + (1 + Semester:Xt |pseudo_ID ),
    data = complete_data,
    family = poisson(link = "log"),
    control = glmerControl(optCtrl = list(maxfun = 1e5),optimizer = "bobyqa")
  )

summary(model_2)



```

## assuming 2307 is female and 5094 is female

```{r}

# constructing variable
load("complete_data3_2307_0_5094_0.RData")

complete_data  = complete_data %>% mutate(
  Pickups_lag_log = log(Pickups_lag),
  Total.ST.min.log = log(Total.ST.min),
  is_work_day = Semester * Xt
)

complete_data <- complete_data %>% 
  group_by(pseudo_ID) %>% 
  mutate(success_lag = lag(success, order_by = Date),
         Total.ST.min.lag = lag(Total.ST.min, order_by = Date),
         Proportion.ST_lag = lag(Proportion.ST, order_by = Date),
         Social.ST.min.lag = lag(Social.ST.min, order_by = Date)
  )

complete_data <- complete_data %>% filter(pseudo_ID != 8622 & pseudo_ID != 9680)

complete_data_A = complete_data %>% filter(Treatment=="A")
complete_data_B = complete_data %>% filter(Treatment=="B")

library(lme4)

model_3 <-
  glmer(
    Pickups ~   Pickups_lag_log + Phase +  Treatment:Phase + Proportion.ST +sex* is_work_day + devices + sex*log(Total.ST.min.lag) + (1 |pseudo_ID ),
    data = complete_data,
    family = poisson(link = "log"),
    control = glmerControl(optCtrl = list(maxfun = 1e5),optimizer = "bobyqa")
  )


lattice::dotplot(ranef(model_3, which = "pseudo_ID", condVar = TRUE), scales = list(y = list(alternating = 0)))
summary(model_3)
```


## on single data B
```{r}

library(lme4)

model_3_B <-
  glmer(
    Pickups ~   Pickups_lag_log +  Phase + Proportion.ST +sex + Semester:Xt + devices + sex*log(Total.ST.min.lag) + (1 + Semester:Xt |pseudo_ID ),
    data = complete_data_B,
    family = poisson(link = "log"),
    control = glmerControl(optCtrl = list(maxfun = 1e5),optimizer = "bobyqa")
  )

summary(model_3_B)

library(broom.mixed)
model_3_B_fixed <- tidy(model_3_B, conf.int = TRUE, effects = "fixed")

library(ggplot2)

ggplot(model_3_B_fixed, aes(x = estimate, y = term, xmin = conf.low, xmax = conf.high)) +
  geom_point(size = 3) +
  geom_errorbarh(height = 0.2) +
  geom_vline(xintercept = 0, color = "red", linetype = "dashed") +
  labs(x = "Coefficient Estimate", y = "Variable", 
       title = "Forest Plot of Fixed Effects") +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5, size = 16),
        axis.title = element_text(size = 14),
        axis.text = element_text(size = 12)) -> model_3_B_result


```

## on single data A
```{r}

library(lme4)

model_3_A <-
  glmer(
    Pickups ~   Pickups_lag_log +  Phase + Proportion.ST +sex + Semester:Xt + devices + sex*log(Total.ST.min.lag) + (1 + Semester:Xt |pseudo_ID ),
    data = complete_data_A,
    family = poisson(link = "log"),
    control = glmerControl(optCtrl = list(maxfun = 1e5),optimizer = "bobyqa")
  )

summary(model_3_A)

library(broom.mixed)
model_3_A_fixed <- tidy(model_3_A, conf.int = TRUE, effects = "fixed")

library(ggplot2)

ggplot(model_3_A_fixed, aes(x = estimate, y = term, xmin = conf.low, xmax = conf.high)) +
  geom_point(size = 3) +
  geom_errorbarh(height = 0.2) +
  geom_vline(xintercept = 0, color = "red", linetype = "dashed") +
  labs(x = "Coefficient Estimate", y = "Variable", 
       title = "Forest Plot of Fixed Effects") +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5, size = 16),
        axis.title = element_text(size = 14),
        axis.text = element_text(size = 12)) -> model_3_A_result


```



```{r}

library(sjPlot)
plot_model(model_3, type = "re")

```


```{r}

library(merTools)
reSims <- REsim(model_3, n.sims = 1000)
plotREsim(reSims)

REsim(model_3, n.sims = 1000) %>% plotREsim() %>% ggsave("plots/REsim_model_3.png",.)

```



# assuming 2307 is female and 5094 is male

```{r}

# constructing variable
load("complete_data3_2307_0_5094_1.RData")

complete_data  = complete_data %>% mutate(
  Pickups_lag_log = log(Pickups_lag),
  Total.ST.min.log = log(Total.ST.min)
)

complete_data <- complete_data %>% 
  group_by(pseudo_ID) %>% 
  mutate(success_lag = lag(success, order_by = Date),
         Total.ST.min.lag = lag(Total.ST.min, order_by = Date),
         Proportion.ST_lag = lag(Proportion.ST, order_by = Date))


library(lme4)

model_4 <-
  glmer(
    Pickups ~   Pickups_lag_log +  Treatment + Phase + Proportion.ST +sex + Semester:Xt + devices + sex:log(Total.ST.min.lag) + (1 + Semester:Xt |pseudo_ID ),
    data = complete_data,
    family = poisson(link = "log"),
    control = glmerControl(optCtrl = list(maxfun = 1e5),optimizer = "bobyqa")
  )

summary(model_4)


```




```{r}


sampler <- function(dat, clustervar, replace = TRUE, reps = 1) {
    cid <- unique(dat[, clustervar[1]])
    ncid <- length(cid)
    recid <- sample(cid, size = ncid * reps, replace = TRUE)
    if (replace) {
        rid <- lapply(seq_along(recid), function(i) {
            cbind(NewID = i, RowID = sample(which(dat[, clustervar] == recid[i]),
                size = length(which(dat[, clustervar] == recid[i])), replace = TRUE))
        })
    } else {
        rid <- lapply(seq_along(recid), function(i) {
            cbind(NewID = i, RowID = which(dat[, clustervar] == recid[i]))
        })
    }
    dat <- as.data.frame(do.call(rbind, rid))
    dat$Replicate <- factor(cut(dat$NewID, breaks = c(1, ncid * 1:reps), include.lowest = TRUE,
        labels = FALSE))
    dat$NewID <- factor(dat$NewID)
    return(dat)
}

```

```{r}

sampler(complete_data, "pseudo_ID", replace = TRUE, reps = 2) 

```
















