---
title: "620PROJECT2"
author: "Xinyu Zhang"
date: "2024-04-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(glm2)
library(readxl)
library(dplyr)

sheet1 = read_excel("Fulldata_620W24_Project2(1).xlsx",sheet=1)
sheet2 = read_excel("Fulldata_620W24_Project2(1).xlsx",sheet=2)

sheet1$pseudo_ID <- as.character(sheet1$pseudo_ID)
sheet2$pseudo_ID <- as.character(sheet2$pseudo_id)

merged_data <- left_join(sheet1, sheet2, by = "pseudo_ID")

data = merged_data %>% mutate(Phase = ifelse(is.na(compliance), 0, 1),
                                             Xt = ifelse(Day %in% c("6", "7"), 0, 1),
                                             Proportion.ST = Social.ST.min/Total.ST.min)
data$Date = data$Date %>% as.Date(.,format="%Y/%m/%d")

data$Semester <- ifelse(data$Date > as.Date("2024-01-09") & !(data$Date >= as.Date("2024-02-24") & data$Date <= as.Date("2024-03-04")), 1, 0)


select_V <- c("Date","pseudo_ID","Total.ST.min","Social.ST.min","Pickups","Proportion.ST","Treatment","sex","pets","devices","procrastination_score", "Phase", "Xt","Semester")
final_data <- data %>% filter(pseudo_ID != 1329 &
                              pseudo_ID != 2520 &
                              pseudo_ID != 2880 &
                              pseudo_ID != 6759 &
                              pseudo_ID != 8622 & 
                              pseudo_ID != 9285 & 
                              pseudo_ID != 2059 & 
                              pseudo_ID != 9680) %>% select(all_of(select_V)) 
sum(is.na(final_data))

```


```{r}
library(mice)
mi.dat <- mice(final_data, method = "pmm", m = 10)
summary(mi.dat)
complete_data_with_date <- complete(mi.dat)
sum(is.na(complete_data_with_date))
save(complete_data_with_date, file = "complete_data_date.RData")
```


